### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by luoxyhappy** [sbelharbi/interpretable-fer-aus#1]
Very grateful for the author's work! Could the author please provide the pretrained model and the code for inference?

**Comment by sbelharbi** [comment]
sure.  will do this week.

**Comment by altunenes** [comment]
thank you for this contribution. a single-image inference would be awesome for mortals like me  :-d

**Comment by sbelharbi** [comment]
hi,
sorry for the delay.
please find [here](https://github.com/sbelharbi/interpretable-fer-aus?tab=readme-ov-file#weights) all (44) the pretrained weights, evaluations scripts for datasets and single image, folds, and facial landmarks.
closing. reopen in case of issue.
thanks

**Comment by altunenes** [comment]
thank you soooooooooooooo much!!!! And all the best...

Enes.
