### ISSUE TITLE
Conversion between 98 key points and 68 key points

### ISSUE THREAD

**Issue by winner-4** [sbelharbi/interpretable-fer-aus#2]
Hello author, first of all, thank you very much for your contribution to the work. I would like to know whether the 98 key points can be converted to 68 key points, because I usually use 98 key points more. If you can provide a conversion list, I will be very grateful.

**Comment by winner-4** [comment]
In addition, could you provide the code to overlay the heat map on the original image?

**Comment by sbelharbi** [comment]
hi,
yes, i think it is easy to convert 98 to 68 points.
i dont have a conversion map but you can try to match the points to go from this
![The-98-facial-landmarks-defined-in-the-WFLW-dataset-Blue-points-are-used-for-the](https://github.com/user-attachments/assets/6f4d90f4-f9ba-4261-bf66-93d889b4caf2)


to this
![Screenshot from 2024-09-12 07-00-22](https://github.com/user-attachments/assets/5b9e9b8d-1fcf-4f59-8a4e-c4794f31acbc)

for eyebrows, you can average the h-coordinates. for eyes, remove the eye-center, and center of top and bottom eye. downsample the jaw.

as for the code to overlay a map over an image, it is usually easy. you can find an example here: https://github.com/sbelharbi/interpretable-fer-aus/blob/66e2bde97a465ced93be20554eaa420a9a490c19/dlib/visualization/vision_wsol.py#L225

and here: https://github.com/sbelharbi/interpretable-fer-aus/blob/66e2bde97a465ced93be20554eaa420a9a490c19/dlib/visualization/vision_wsol.py#L106

thanks

**Comment by winner-4** [comment]
Thank you.
